### ISSUE TITLE
Formatting issue on TOML and text files links - Newlines removed

### ISSUE THREAD

**Issue by damascene** [nosdav/pastebin#14]
Storing files using `paste.toml` as name and TOML content produces a link to file that displays non valid TOML file with all new lines removed. I've noticed similar issue with text format also. JSON files with `.json` extension are displayed correctly.

Original toml:

```toml
# This is a TOML document

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00

[database]
enabled = true
ports = [ 8000, 8001, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0 }

[servers]

[servers.alpha]
ip = "10.0.0.1"
role = "frontend"

[servers.beta]
ip = "10.0.0.2"
role = "backend"
```

Result on the link:

```text
# This is a TOML document title = "TOML Example" [owner] name = "Tom Preston-Werner" dob = 1979-05-27T07:32:00-08:00 [database] enabled = true ports = [ 8000, 8001, 8002 ] data = [ ["delta", "phi"], [3.14] ] temp_targets = { cpu = 79.5, case = 72.0 } [servers] [servers.alpha] ip = "10.0.0.1" role = "frontend" [servers.beta] ip = "10.0.0.2" role = "backend" 
```

However using the **load** button inside the editor can still retrieve a well formatted toml file. Issue seems is when you open the file link.
```
https://nosdav.net/...................../paste.toml
```

I've tested with json file and there was no issue.

**Comment by melvincarvalho** [comment]
Thanks, I dont yet support .toml mime type, which are listed here:

https://github.com/nosdav/server/blob/gh-pages/index.js#L50

I'll try and fix this later today and redeploy the server

**Comment by melvincarvalho** [comment]
I looked at this a bit more, actually it's saving fine, its just the browser displays text like that without newlines

see:

https://nosdav.net/de7ecd1e2976a6adb2ffa5f4db81a7d812c8bb6698aa00dcf1e76adb55efd645/test.toml

But if you view browser source you get

![image](https://github.com/nosdav/pastebin/assets/65864/bd5dfee3-b522-4b4d-9fcf-ac02261e0b45)

Also try 
```bash
curl https://nosdav.net/de7ecd1e2976a6adb2ffa5f4db81a7d812c8bb6698aa00dcf1e76adb55efd645/test.toml
```

```toml
# This is a TOML document

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00

[database]
enabled = true
ports = [ 8000, 8001, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0 }

[servers]

[servers.alpha]
ip = "10.0.0.1"
role = "frontend"

[servers.beta]
ip = "10.0.0.2"
```

So this should be working
